#Text Representation methods based on word embeddings

*   word2vec - Google
*   Glove - Stanford
*   fasttext - Facebook






Exploring the pretrained word embedding models and datasets

In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 66.3 MB/s eta 0:00:00


In [ ]:
import gensim.downloader as api

In [ ]:
api.info()

{'corpora': {'semeval-2016-2017-task3-subtaskBC': {'num_records': -1,
   'record_format': 'dict',
   'file_size': 6344358,
   'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/semeval-2016-2017-task3-subtaskB-eng/__init__.py',
   'license': 'All files released for the task are free for general research use',
   'fields': {'2016-train': ['...'],
    '2016-dev': ['...'],
    '2017-test': ['...'],
    '2016-test': ['...']},
   'description': 'SemEval 2016 / 2017 Task 3 Subtask B and C datasets contain train+development (317 original questions, 3,169 related questions, and 31,690 comments), and test datasets in English. The description of the tasks and the collected data is given in sections 3 and 4.1 of the task paper http://alt.qcri.org/semeval2016/task3/data/uploads/semeval2016-task3-report.pdf linked in section “Papers” of https://github.com/RaRe-Technologies/gensim-data/issues/18.',
   'checksum': '701ea67acd82e75f95e1d8e62fb0ad29',
   'file_name': 'se

In [ ]:
pretrained_word2vec_model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
pretrained_word2vec_model["dog"]#It gives the vector of a given word

array([ 5.12695312e-02, -2.23388672e-02, -1.72851562e-01,  1.61132812e-01,
       -8.44726562e-02,  5.73730469e-02,  5.85937500e-02, -8.25195312e-02,
       -1.53808594e-02, -6.34765625e-02,  1.79687500e-01, -4.23828125e-01,
       -2.25830078e-02, -1.66015625e-01, -2.51464844e-02,  1.07421875e-01,
       -1.99218750e-01,  1.59179688e-01, -1.87500000e-01, -1.20117188e-01,
        1.55273438e-01, -9.91210938e-02,  1.42578125e-01, -1.64062500e-01,
       -8.93554688e-02,  2.00195312e-01, -1.49414062e-01,  3.20312500e-01,
        3.28125000e-01,  2.44140625e-02, -9.71679688e-02, -8.20312500e-02,
       -3.63769531e-02, -8.59375000e-02, -9.86328125e-02,  7.78198242e-03,
       -1.34277344e-02,  5.27343750e-02,  1.48437500e-01,  3.33984375e-01,
        1.66015625e-02, -2.12890625e-01, -1.50756836e-02,  5.24902344e-02,
       -1.07421875e-01, -8.88671875e-02,  2.49023438e-01, -7.03125000e-02,
       -1.59912109e-02,  7.56835938e-02, -7.03125000e-02,  1.19140625e-01,
        2.29492188e-01,  

In [ ]:
len(pretrained_word2vec_model["dog"])#Checking vector dimensions

300

In [ ]:
pretrained_word2vec_model.most_similar("dog")

[('dogs', 0.8680489659309387),
 ('puppy', 0.8106428384780884),
 ('pit_bull', 0.780396044254303),
 ('pooch', 0.7627376914024353),
 ('cat', 0.7609457969665527),
 ('golden_retriever', 0.7500901818275452),
 ('German_shepherd', 0.7465174198150635),
 ('Rottweiler', 0.7437615394592285),
 ('beagle', 0.7418621778488159),
 ('pup', 0.740691065788269)]

#1. Data Acquisiton

In [ ]:
import pandas as pd

In [ ]:
amazon_df  = pd.read_csv("amazon_cells_labelled.txt",sep='\t',header=None)

In [ ]:
yelp_df = pd.read_csv("yelp_labelled.txt",sep='\t', header=None)

In [ ]:
imdb_df = pd.read_csv("imdb_labelled.txt",sep='\t',header=None)

In [ ]:
#Combining all the datasets into one big dataset
master_df = pd.concat([amazon_df,yelp_df,imdb_df])

In [ ]:
master_df

0  1
0    So there is no way for me to plug it in here i...  0
1                          Good case, Excellent value.  1
2                               Great for the jawbone.  1
3    Tied to charger for conversations lasting more...  0
4                                    The mic is great.  1
..                                                 ... ..
743  I just got bored watching Jessice Lange take h...  0
744  Unfortunately, any virtue in this film's produ...  0
745                   In a word, it is embarrassing.    0
746                               Exceptionally bad!    0
747  All in all its an insult to one's intelligence...  0

[2748 rows x 2 columns]

In [ ]:
master_df[1].value_counts()

1
1    1386
0    1362
Name: count, dtype: int64

#2. Text Cleaning & Pre-processing

In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

In [ ]:
def clean_preprocess(text):
  #Lowercasing
  text = text.lower()
  #Removing punctuation and digits
  doc = nlp(text)
  text = [token.text  for token in doc if (not token.is_punct) and (not token.like_num)]
  #Removing stopwords
  preprocessed_text = [word for word in text if word not in ENGLISH_STOP_WORDS]
  #preprocessed_text = ' '.join(text)#Joining list of word into a sentence
  return preprocessed_text

In [ ]:
master_df[0] = master_df[0].apply(lambda row: clean_preprocess(row))

In [ ]:
master_df

0  1
0                       [way, plug, unless, converter]  0
1                       [good, case, excellent, value]  1
2                                     [great, jawbone]  1
3    [tied, charger, conversations, lasting, minute...  0
4                                         [mic, great]  1
..                                                 ... ..
743  [just, got, bored, watching, jessice, lange, c...  0
744  [unfortunately, virtue, film, 's, production, ...  0
745                            [word, embarrassing,  ]  0
746                            [exceptionally, bad,  ]  0
747  [insult, 's, intelligence, huge, waste, money,  ]  0

[2748 rows x 2 columns]

#3. Text Representation or Feature Engineering (using word2vec pretrained model)

In [ ]:
import numpy as np

In [ ]:
def convert_word_to_vector(text):
  total_vector = []
  for row in text:#Iterating each row in the text column of the dataset
    count = 0
    row_total_vector = np.zeros(300) #initializing with the zeros of the same size as vector
    for word in row:#Iterating over each word in a row
      if word in pretrained_word2vec_model:
        row_total_vector = row_total_vector + pretrained_word2vec_model[word]
        count = count + 1
    if count != 0:
      row_avg_vector = row_total_vector/count
      total_vector.append(row_avg_vector)
    else:
      total_vector.append(np.zeros(300))


  return total_vector


In [ ]:
X_vector = convert_word_to_vector(master_df[0])

In [ ]:
np.shape(X_vector)

(2748, 300)

In [ ]:
np.shape(master_df[1])

(2748,)

#4. Training the model

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_vector,master_df[1],random_state=1)

In [ ]:
np.shape(X_train)

(2061, 300)

In [ ]:
np.shape(X_test)

(687, 300)

In [ ]:
model = LogisticRegression()#Defining the M.L. Algorithm
model.fit(X_train, y_train) #Training the model

LogisticRegression()

In [ ]:
#Testing the model with the test data
y_pred = model.predict(X_test)

#5. Evaluating the model

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_pred, y_test)

0.8296943231441049

In [ ]:
model.score(X_test,y_test)

0.8296943231441049

#6. Applying or using the model

In [ ]:
review = "I hate this movie"

In [ ]:
processed_text = clean_preprocess(review)

In [ ]:
sample_vector = convert_word_to_vector([processed_text])

In [ ]:
sentiment_score = model.predict(sample_vector)

In [ ]:
sentiment_score

array([0])

In [ ]:
import pickle

# Save the trained model to a file
with open('sentiment_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!


In [ ]:
import pickle

# Load the saved model from the file
with open('sentiment_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

print("Model loaded successfully!")

Model loaded successfully!


In [ ]:
loaded_model.predict(sample_vector)

array([0])